api-version: '1.17'
author: Epicnicity322
depend: [ EpicPluginLib ]
description: A fast and simple terrain claiming plugin.
folia-supported: true
main: com.epicnicity322.terrainer.bukkit.TerrainerPlugin
name: Terrainer
softdepend: [ PlaceholderAPI, Vault, WorldEdit ]
version: '1.0'

commands:
  terrainer:
    aliases: [ tr,terrain ]
    description: Terrainer's main command.
    permission: terrainer

permissions:
  terrainer:
    description: 'Allows use of Terrainer''s main command: /terrain'
    default: true

  terrainer.admin:
    description: Recommended admin permissions.
    default: op
    children:
      terrainer.player: true
      terrainer.bypass.build: true
      terrainer.bypass.cooldown.transfer: true
      terrainer.bypass.cooldown.infowand: true
      terrainer.bypass.cooldown.selectorwand: true
      terrainer.bypass.limit.blocks: true
      terrainer.bypass.limit.claims: true
      terrainer.bypass.name-blacklist: true
      terrainer.bypass.name-length: true
      terrainer.bypass.overlap: true
      terrainer.define: true
      terrainer.description.others: true
      terrainer.flag.*: true
      terrainer.info.console: true
      terrainer.info.world: true
      terrainer.limit.edit: true
      terrainer.list.others: true
      terrainer.priority.others: true
      terrainer.priority.world: true
      terrainer.reload: true
      terrainer.rename.others: true
      terrainer.resize.others: true
      terrainer.select.command.3d: true
      terrainer.select.command.3d.coordinates: true
      terrainer.select.command.3d.coordinates.world: true
      terrainer.select.command.coordinates: true
      terrainer.select.command.coordinates.world: true
      terrainer.teleport: true
      terrainer.teleport.nodelay: true
      terrainer.teleport.otherplayers: true
      terrainer.teleport.otherterrains: true
      terrainer.transfer.console: true
      terrainer.transfer.force: true
      terrainer.transfer.others: true
      terrainer.transfer.toconsole: true
      terrainer.updateavailablealert: true
      terrainer.wand.info.free: true
      terrainer.wand.info: true
      terrainer.wand.others: true
      terrainer.wand.selector.free: true

  terrainer.player:
    description: Recommended player permissions.
    default: true
    children:
      terrainer.borders.show: true
      terrainer.borders: true
      terrainer.bypass.overlap.self: true
      terrainer.claim: true
      terrainer.delete: true
      terrainer.description: true
      terrainer.grant: true
      terrainer.help: true
      terrainer.info.others: true
      terrainer.info.wand: true
      terrainer.info: true
      terrainer.limit.blocks.default: true
      terrainer.limit.claims.default: true
      terrainer.limit: true
      terrainer.list: true
      terrainer.player.flags: true
      terrainer.priority: true
      terrainer.priority.overlappinginfo: true
      terrainer.rename: true
      terrainer.resize: true
      terrainer.revoke: true
      terrainer.select.command: true
      terrainer.select.wand: true
      terrainer.sell: true
      terrainer.shop.blocks: true
      terrainer.shop.claims: true
      terrainer.shop: true
      terrainer.transfer: true
      terrainer.wand.others: true
      terrainer.wand.selector: true
      terrainer.wand: true
      terrainer.world.world: true

  terrainer.player.flags:
    description: Recommended flags for players.
    default: false
    children:
      terrainer.flag: true
      terrainer.flag.anvils: true
      terrainer.flag.armorstands: true
      terrainer.flag.build: true
      terrainer.flag.buildvehicles: true
      terrainer.flag.buttons: true
      terrainer.flag.containers: true
      terrainer.flag.dispensers: true
      terrainer.flag.doors: true
      terrainer.flag.entervehicles: true
      terrainer.flag.entityharm: true
      terrainer.flag.entityinteractions: true
      terrainer.flag.frostwalk: true
      terrainer.flag.interactions: true
      terrainer.flag.itemdrop: true
      terrainer.flag.itemframes: true
      terrainer.flag.itempickup: true
      terrainer.flag.leavemessage: true
      terrainer.flag.messagelocation: true
      terrainer.flag.mobspawn: true
      terrainer.flag.modscaneditflags: true
      terrainer.flag.modscanmanagemods: true
      terrainer.flag.outsidedispensers: true
      terrainer.flag.outsidepistons: true
      terrainer.flag.outsideprojectiles: true
      terrainer.flag.pistons: true
      terrainer.flag.pressureplates: true
      terrainer.flag.projectiles: true
      terrainer.flag.pvp: true
      terrainer.flag.signclick: true
      terrainer.flag.signedit: true
      terrainer.flag.spawners: true
      terrainer.flag.trample: true

  terrainer.flag.*:
    description: Permission for all flags of terrainer.
    default: false
    children:
      terrainer.flag.effects: true
      terrainer.flag.enemyharm: true
      terrainer.flag.enter: true
      terrainer.flag.explosiondamage: true
      terrainer.flag.firedamage: true
      terrainer.flag.fly: true
      terrainer.flag.glide: true
      terrainer.flag.leafdecay: true
      terrainer.flag.leave: true
      terrainer.flag.liquidflow: true
      terrainer.flag.prepare: true
      terrainer.flag.vulnerability: true
      terrainer.player.flag: true

  terrainer.claim:
    description: Allows users to use the command '/tr claim [name]', to claim terrains from their selection.
    default: false

  terrainer.flag:
    description: Allows players to toggle flags using the Flag Management GUI, or through the command '/tr flag <flag> [args] [-t <terrain>]'.
    default: false

  terrainer.bypass.build:
    description: Allows players to build in any terrain, even if they are not a member of the terrain.
    default: false

  terrainer.bypass.overlap:
    description: Allows players to select and claim terrains over other terrains they do not own.
    default: false

  terrainer.bypass.limit.claims:
    description: Allows players to have unlimited terrains.
    default: false

  terrainer.bypass.limit.blocks:
    description: Allows players to claim terrains with unlimited area.
    default: false

  terrainer.select.command:
    description: Allows players to select to their current position using the commands '/tr pos1' or '/tr pos2'.
    default: false

  terrainer.select.command.coordinates:
    description: Allows users to select to a coordinate using the command '/tr <pos1|pos2> <x> <y> <z> [world]'.
    default: false
    children:
      terrainer.select.command: true

  terrainer.select.wand:
    description: Allows players to select using the Terrainer Selection Wand.
    default: false

  terrainer.wand:
    description: Allows players to get the Terrainer Selection Wand item using the command '/tr wand'.
    default: false
    children:
      terrainer.select.wand: true

  terrainer.world.<worldname>:
    description: Allows players to claim or select terrains in this world.
    default: false

  terrainer.3d:
    description: Allows players to select and make terrains with different heights.
    default: false

  terrainer.limit:
    description: Allows players to see their own limits with '/tr limit'.
    default: false

  terrainer.limit.others:
    description: Allows players to see limits of other players with '/tr limit <player>'.
    default: false
    children:
      terrainer.limit: true

  terrainer.limit.claims.Default:
    description: Defines a player limit based on the value set on config node 'Claim Limits.Default'.
    default: false

  terrainer.limit.claims.VIP:
    description: Defines a player limit based on the value set on config node 'Claim Limits.VIP'.
    default: false

  terrainer.limit.claims.Staff:
    description: Defines a player limit based on the value set on config node 'Claim Limits.Staff'.
    default: false

  terrainer.limit.blocks.Default:
    description: Defines a player limit based on the value set on config node 'Block Limits.Default'.
    default: false

  terrainer.limit.blocks.VIP:
    description: Defines a player limit based on the value set on config node 'Block Limits.VIP'.
    default: false

  terrainer.limit.blocks.Staff:
    description: Defines a player limit based on the value set on config node 'Block Limits.Staff'.
    default: false

  terrainer.limit.edit:
    description: Allows players to edit limits with '/tr limit <player> <give|set|take> <blocks|claims> <amount>'.
    default: false
    children:
      terrainer.limit.others: true
      terrainer.limit.edit.blocks: true
      terrainer.limit.edit.claims: true

  terrainer.limit.edit.blocks:
    description: Allows players to edit block limits.
    default: false
    children:
      terrainer.limit: true

  terrainer.limit.edit.claims:
    description: Allows players to edit claim limits.
    default: false
    children:
      terrainer.limit: true

  terrainer.reload:
    description: Allows users to reload configurations using the command '/tr reload'.
    default: false